"""Pydantic schemas, grouped by domain."""
from app.schemas.auth import (
    CurrentUser,
    LoginRequest,
    LoginResponse,
    PasswordChangeRequest,
    RefreshRequest,
    StudentContext,
    TokenPair,
)
from app.schemas.common import (
    IIN,
    LabeledValue,
    Message,
    ORMModel,
    Page,
    Password,
    PersonName,
    PhoneNumber,
)
from app.schemas.content import (
    AnswerRead,
    MediaRead,
    QuestionRead,
    TopicBrief,
    TopicDetail,
    VideoRead,
)
from app.schemas.quiz import (
    AnswerRequest,
    AnswerResult,
    ItemState,
    MistakeReview,
    QuestionReview,
    QuizStartRequest,
    ResultBrief,
    SessionRead,
    SessionResult,
)
from app.schemas.user import (
    CredentialsIssued,
    ManagerCreate,
    ManagerUpdate,
    StudentCreate,
    StudentRead,
    StudentUpdate,
    UserBrief,
)

__all__ = [
    "IIN",
    "AnswerRead",
    "AnswerRequest",
    "AnswerResult",
    "CredentialsIssued",
    "CurrentUser",
    "ItemState",
    "LabeledValue",
    "LoginRequest",
    "LoginResponse",
    "ManagerCreate",
    "ManagerUpdate",
    "MediaRead",
    "Message",
    "MistakeReview",
    "QuestionReview",
    "ORMModel",
    "Page",
    "Password",
    "PasswordChangeRequest",
    "PersonName",
    "PhoneNumber",
    "QuestionRead",
    "QuizStartRequest",
    "RefreshRequest",
    "ResultBrief",
    "SessionRead",
    "SessionResult",
    "StudentContext",
    "StudentCreate",
    "StudentRead",
    "StudentUpdate",
    "TokenPair",
    "TopicBrief",
    "TopicDetail",
    "UserBrief",
    "VideoRead",
]
