"""quiz time limit

Revision ID: de73f7279eb4
Revises: 8b37b582b008
Create Date: 2026-08-29 00:56:37.793183
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'de73f7279eb4'
down_revision: str | None = '8b37b582b008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('time_limit_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'time_limit_seconds')
    # ### end Alembic commands ###
